apiVersion: v1
kind: Service
metadata:
  name: usdt-listener-service
spec:
  type: NodePort
  selector:
    app: usdt-listener
  ports:
    - protocol: TCP
      port: 3000 # 클러스터 내부에서 사용할 포트
      targetPort: 3000 # 컨테이너에서 열고 있는 포트
      nodePort: 32000 # 브라우저 접근 포트 (VM IP:32000)
