apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usdt-listener
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourname/k8s-web3-monitor.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
