apiVersion: apps/v1
kind: Deployment
metadata:
  name: usdt-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usdt-worker
  template:
    metadata:
      labels:
        app: usdt-worker
    spec:
      restartPolicy: Always
      containers:
        - name: usdt-worker
          image: seowlee/usdt-worker:latest
          env:
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: MONGO_URL
              value: "mongodb://mongo-service:27017"
            - name: MONGO_DB
              value: "web3monitor"
            - name: MONGO_COLLECTION
              value: "usdtTransfers"
